services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=settlement_randomizer
      - MYSQL_USER=api
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    command:
      - --require_secure_transport=OFF
      - --bind-address=0.0.0.0
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:3000"
    volumes:
      - $PWD/db/certs:/usr/src/app/certs
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: